<a href="https://colab.research.google.com/github/AtulMomre2327/Intro-to-Machine-Learning/blob/main/Classificaation_all_model_use.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/adult.csv')

In [ ]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [ ]:
df.shape

(32561, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [ ]:
df['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [ ]:
df = pd.get_dummies(
    df,
    columns=[
        'workclass',
        'education',
        'marital.status',
        'occupation',
        'relationship',
        'race',
        'sex',
        'native.country'
    ],
    drop_first=True
)

In [ ]:
df['income'] = df['income'].map({'<=50K':0,'>50K':1})

In [ ]:
df['income'].value_counts()

income
0    24720
1     7841
Name: count, dtype: int64

In [ ]:
df.columns

Index(['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss',
       'hours.per.week', 'income', 'workclass_Federal-gov',
       'workclass_Local-gov', 'workclass_Never-worked',
       ...
       'native.country_Portugal', 'native.country_Puerto-Rico',
       'native.country_Scotland', 'native.country_South',
       'native.country_Taiwan', 'native.country_Thailand',
       'native.country_Trinadad&Tobago', 'native.country_United-States',
       'native.country_Vietnam', 'native.country_Yugoslavia'],
      dtype='object', length=101)

In [ ]:
x = df.drop('income', axis=1)
y = df['income']

In [ ]:
x.head()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
0,90,77053,9,0,4356,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,82,132870,9,0,4356,18,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,66,186061,10,0,4356,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,54,140359,4,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,41,264663,10,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: income, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
from  sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score,recall_score,f1_score

In [ ]:
print('Train Confusion Matrix :-\n',confusion_matrix(y_train,train_pred))
print('Train Accuracy :-',accuracy_score(y_train,train_pred))
print('Train Precision :-',precision_score(y_train,train_pred))
print('Train Recall :-',recall_score(y_train,train_pred))

Train Confusion Matrix :-
 [[19109   635]
 [ 4665  1639]]
Train Accuracy :- 0.796529484029484
Train Precision :- 0.7207563764291997
Train Recall :- 0.25999365482233505

In [ ]:
print('Test Confusion Matrix :-\n',confusion_matrix(y_test,test_pred))
print('Test Accuracy :-',accuracy_score(y_test,test_pred))
print('Test Precision :-',precision_score(y_test,test_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Test Confusion Matrix :-
 [[4815  161]
 [1161  376]]
Test Accuracy :- 0.7970213419315215
Test Precision :- 0.7001862197392924
Test Recall :- 0.2446324007807417

** DecisionTreeClassifier **

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier()

In [ ]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score,recall_score,f1_score

In [ ]:
print('Train Confusion Matrix :-\n',confusion_matrix(y_train,train_pred))
print('Train Accuracy :-',accuracy_score(y_train,train_pred))
print('Train Precision :-',precision_score(y_train,train_pred))
print('Train Recall :-',recall_score(y_train,train_pred))

Train Confusion Matrix :-
 [[19744     0]
 [    1  6303]]
Train Accuracy :- 0.9999616093366094
Train Precision :- 1.0
Train Recall :- 0.9998413705583756

In [ ]:
print('Test Confusion Matrix :-\n',confusion_matrix(y_test,test_pred))
print('Test Accuracy :-',accuracy_score(y_test,test_pred))
print('Test Precision :-',precision_score(y_test,test_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Test Confusion Matrix :-
 [[4372  604]
 [ 590  947]]
Test Accuracy :- 0.8166743436204514
Test Precision :- 0.6105738233397808
Test Recall :- 0.616135328562134

## RandomForestClassifre

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier()

In [ ]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:

print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19744
           1       1.00      1.00      1.00      6304

    accuracy                           1.00     26048
   macro avg       1.00      1.00      1.00     26048
weighted avg       1.00      1.00      1.00     26048

In [ ]:

print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.93      0.90      4976
           1       0.71      0.60      0.65      1537

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.78      6513
weighted avg       0.84      0.85      0.84      6513

In [ ]:
print('Train Confusion Matrix :-\n',confusion_matrix(y_train,train_pred))
print('Train Accuracy :-',accuracy_score(y_train,train_pred))
print('Train Precision :-',precision_score(y_train,train_pred))
print('Train Recall :-',recall_score(y_train,train_pred))

Train Confusion Matrix :-
 [[19744     0]
 [    1  6303]]
Train Accuracy :- 0.9999616093366094
Train Precision :- 1.0
Train Recall :- 0.9998413705583756

In [ ]:
print('Test Confusion Matrix :-\n',confusion_matrix(y_test,test_pred))
print('Test Accuracy :-',accuracy_score(y_test,test_pred))
print('Test Precision :-',precision_score(y_test,test_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Test Confusion Matrix :-
 [[4604  372]
 [ 612  925]]
Test Accuracy :- 0.8489175495163519
Test Precision :- 0.7131842713955281
Test Recall :- 0.6018217306441119

## GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
model = GradientBoostingClassifier()

In [ ]:

model.fit(x_train,y_train)

GradientBoostingClassifier()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:

print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92     19744
           1       0.80      0.61      0.70      6304

    accuracy                           0.87     26048
   macro avg       0.84      0.78      0.81     26048
weighted avg       0.87      0.87      0.86     26048

In [ ]:

print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      4976
           1       0.79      0.58      0.67      1537

    accuracy                           0.86      6513
   macro avg       0.84      0.77      0.79      6513
weighted avg       0.86      0.86      0.86      6513

## GridSearchCV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:

param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5]
}

In [ ]:

model = GridSearchCV(
    estimator=GradientBoostingClassifier(),
    param_grid=param_grid,
    cv=3,
    verbose=2,
    n_jobs=-1
)

In [ ]:
model.fit(x_train,y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1], 'max_depth': [3, 5],
                         'n_estimators': [100, 200]},
             verbose=2)

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.90     19744
           1       0.76      0.45      0.57      6304

    accuracy                           0.83     26048
   macro avg       0.80      0.70      0.73     26048
weighted avg       0.82      0.83      0.82     26048

In [ ]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86      4976
           1       0.56      0.30      0.39      1537

    accuracy                           0.78      6513
   macro avg       0.68      0.61      0.63      6513
weighted avg       0.75      0.78      0.75      6513

## GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model = GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       0.81      0.95      0.88     19744
           1       0.66      0.31      0.43      6304

    accuracy                           0.80     26048
   macro avg       0.74      0.63      0.65     26048
weighted avg       0.78      0.80      0.77     26048

In [ ]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.81      0.95      0.88      4976
           1       0.64      0.30      0.41      1537

    accuracy                           0.79      6513
   macro avg       0.73      0.62      0.64      6513
weighted avg       0.77      0.79      0.77      6513

## KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model = KNeighborsClassifier()

In [ ]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.90     19744
           1       0.76      0.45      0.57      6304

    accuracy                           0.83     26048
   macro avg       0.80      0.70      0.73     26048
weighted avg       0.82      0.83      0.82     26048

In [ ]:
confusion_matrix(y_train,train_pred)

array([[18843,   901],
       [ 3461,  2843]])

In [ ]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86      4976
           1       0.56      0.30      0.39      1537

    accuracy                           0.78      6513
   macro avg       0.68      0.61      0.63      6513
weighted avg       0.75      0.78      0.75      6513

In [ ]:
confusion_matrix(y_test,test_pred)

array([[4605,  371],
       [1070,  467]])

## VotingClassifier

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(max_iter=500)),
        ('dt', DecisionTreeClassifier()),
        ('svm', SVC(probability=True))
    ],
    voting='hard'
)

model.fit(x_train, y_train)

prediction = model.predict(x_test)

print("Accuracy :", accuracy_score(y_test, prediction))

Accuracy : 0.8413941348073085

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.93     19744
           1       1.00      0.51      0.67      6304

    accuracy                           0.88     26048
   macro avg       0.93      0.75      0.80     26048
weighted avg       0.90      0.88      0.87     26048

In [ ]:
confusion_matrix(y_train,train_pred)

array([[19729,    15],
       [ 3106,  3198]])

In [ ]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.84      0.97      0.90      4976
           1       0.83      0.41      0.55      1537

    accuracy                           0.84      6513
   macro avg       0.84      0.69      0.73      6513
weighted avg       0.84      0.84      0.82      6513