<a href="https://colab.research.google.com/github/AtulMomre2327/Intro-to-Machine-Learning/blob/main/Ensembles_Learning_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble  import  GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score,confusion_matrix,accuracy_score,classification_report

In [18]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/Manufacturing_dataset.csv')

In [19]:
df.head()

             Timestamp  ...  Optimal Conditions
0  2025-04-01 08:00:00  ...                   0
1  2025-04-01 08:01:00  ...                   0
2  2025-04-01 08:02:00  ...                   0
3  2025-04-01 08:03:00  ...                   0
4  2025-04-01 08:04:00  ...                   0

[5 rows x 7 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Timestamp                 10000 non-null  object
 1   Temperature (°C)          10000 non-null  float64
 2   Machine Speed (RPM)       10000 non-null  int64
 3   Production Quality Score  10000 non-null  float64
 4   Vibration Level (mm/s)    10000 non-null  float64
 5   Energy Consumption (kWh)  10000 non-null  float64
 6   Optimal Conditions        10000 non-null  int64
dtypes: float64(4), int64(2), object(1)
memory usage: 547.0+ KB

In [32]:
df = df.drop('Timestamp', axis=1)

In [33]:
df['Optimal Conditions'].value_counts()

Optimal Conditions
0    9034
1     966
Name: count, dtype: int64

In [34]:
x = df.drop('Optimal Conditions',axis=1)
y = df['Optimal Conditions']

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [36]:
classifier = RandomForestClassifier()
grid_value = {'n_estimators':[10,20,30,40,50,60,],'max_depth':[10,20,30,]}
classifier = GridSearchCV(classifier, param_grid = grid_value, scoring = 'roc_auc', cv=5)

In [37]:
model = RandomForestClassifier()

In [38]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [43]:
train_pred = model.predict(x_train)

In [44]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7227
           1       1.00      1.00      1.00       773

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

In [45]:
confusion_matrix(y_train,train_pred)

array([[7227,    0],
       [   0,  773]])

In [47]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1807
           1       1.00      1.00      1.00       193

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [48]:
confusion_matrix(y_test,test_pred)

array([[1807,    0],
       [   0,  193]])

In [49]:
model = GradientBoostingClassifier()

In [50]:
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [51]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [52]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7227
           1       1.00      1.00      1.00       773

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

In [53]:
confusion_matrix(y_train,train_pred)

array([[7227,    0],
       [   0,  773]])

In [54]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1807
           1       1.00      1.00      1.00       193

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [91]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [92]:
model = BaggingClassifier(estimator=DecisionTreeClassifier(),
        n_estimators = 50,
        random_state = 42)

In [93]:
model.fit(x_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50,
                  random_state=42)

In [94]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [95]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7191
           1       1.00      1.00      1.00      7263

    accuracy                           1.00     14454
   macro avg       1.00      1.00      1.00     14454
weighted avg       1.00      1.00      1.00     14454

In [96]:
confusion_matrix(y_train,train_pred)

array([[7191,    0],
       [   0, 7263]])

In [97]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1843
           1       1.00      1.00      1.00      1771

    accuracy                           1.00      3614
   macro avg       1.00      1.00      1.00      3614
weighted avg       1.00      1.00      1.00      3614

In [98]:
confusion_matrix(y_test,test_pred)

array([[1843,    0],
       [   0, 1771]])

In [99]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [100]:
model = VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(max_iter=500)),
        ('dt', DecisionTreeClassifier()),
        ('svm', SVC(probability=True))
    ],
    voting='hard'
)

model.fit(x_train, y_train)

prediction = model.predict(x_test)

print("Accuracy :", accuracy_score(y_test, prediction))

Accuracy : 0.8348090758162701

In [101]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [102]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80      7191
           1       0.75      1.00      0.86      7263

    accuracy                           0.84     14454
   macro avg       0.88      0.84      0.83     14454
weighted avg       0.88      0.84      0.83     14454

In [103]:
confusion_matrix(y_train,train_pred)

array([[4819, 2372],
       [   0, 7263]])

In [104]:
df['Optimal Conditions'].value_counts()

Optimal Conditions
0    9034
1     966
Name: count, dtype: int64

In [105]:
from imblearn.over_sampling import SMOTE

In [106]:
y.value_counts()

Optimal Conditions
0    9034
1     966
Name: count, dtype: int64

In [107]:
x_smote,y_smote = SMOTE().fit_resample(x,y)

In [108]:
y_smote.value_counts()
#

Optimal Conditions
0    9034
1    9034
Name: count, dtype: int64

In [109]:
x_train,x_test,y_train,y_test = train_test_split(x_smote,y_smote,test_size=0.2,random_state=42)

In [110]:
model  = LogisticRegression()

In [111]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [112]:
prediction = model.predict(x_test)

In [113]:
print("Accuracy", accuracy_score(y_test,prediction))

Accuracy 0.7468179302711677

In [114]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [115]:
print(classification_report(y_train,train_pred))

              precision    recall  f1-score   support

           0       0.79      0.66      0.72      7191
           1       0.71      0.82      0.76      7263

    accuracy                           0.75     14454
   macro avg       0.75      0.74      0.74     14454
weighted avg       0.75      0.75      0.74     14454

In [116]:
confusion_matrix(y_train,train_pred)

array([[4781, 2410],
       [1272, 5991]])

In [117]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.80      0.67      0.73      1843
           1       0.71      0.82      0.76      1771

    accuracy                           0.75      3614
   macro avg       0.75      0.75      0.75      3614
weighted avg       0.75      0.75      0.75      3614

In [118]:
confusion_matrix(y_test,test_pred)

array([[1239,  604],
       [ 311, 1460]])