<a href="https://colab.research.google.com/github/AtulMore2327/Intro-to-Machine-Learning/blob/main/Notebook_1_Overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:

# df1 = Shipments (Main Table)
df1 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/shipments.csv")

# df2 = Customers
df2 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/customers.csv")

# df3 = Products
df3 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/products.csv")

# df4 = Carriers
df4 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/carriers.csv")

# df5 = Routes
df5 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/routes.csv")

# df6 = Vehicles
df6 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/vehicles.csv")

# df7 = Warehouses
df7 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/warehouses.csv")

# df8 = Customs
df8 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/customs.csv")

# df9 = Weather
df9 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/weather.csv")

# df10 = Shipment Delivery History
df10 = pd.read_csv("/content/drive/MyDrive/Data  Set/raw_data/shipment_delivery_history.csv")

In [5]:
print("df1 :", df1.shape)
print("df2 :", df2.shape)
print("df3 :", df3.shape)
print("df4 :", df4.shape)
print("df5 :", df5.shape)
print("df6 :", df6.shape)
print("df7 :", df7.shape)
print("df8 :", df8.shape)
print("df9 :", df9.shape)
print("df10:", df10.shape)

df1 : (4060, 21)
df2 : (624, 9)
df3 : (164, 10)
df4 : (30, 7)
df5 : (300, 11)
df6 : (300, 7)
df7 : (50, 7)
df8 : (1800, 6)
df9 : (1200, 9)
df10: (4020, 5)

In [6]:
## Shipments

In [7]:
df1.shape

(4060, 21)

In [8]:
df1.columns

Index(['shipment_id', 'booking_id', 'customer_id', 'product_id', 'carrier_id',
       'warehouse_id', 'route_id', 'vehicle_id', 'customs_id', 'weather_id',
       'booking_date', 'ship_date', 'expected_delivery_date', 'shipping_mode',
       'shipment_type', 'priority', 'weight_kg', 'volume_cbm',
       'declared_value', 'insurance', 'fragile'],
      dtype='object')

In [9]:
df1.dtypes

shipment_id                object
booking_id                 object
customer_id                object
product_id                 object
carrier_id                 object
warehouse_id               object
route_id                   object
vehicle_id                 object
customs_id                 object
weather_id                 object
booking_date               object
ship_date                  object
expected_delivery_date     object
shipping_mode              object
shipment_type              object
priority                   object
weight_kg                 float64
volume_cbm                float64
declared_value            float64
insurance                    bool
fragile                      bool
dtype: object

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4060 entries, 0 to 4059
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4060 non-null   object
 1   booking_id              4060 non-null   object
 2   customer_id             4060 non-null   object
 3   product_id              4060 non-null   object
 4   carrier_id              4060 non-null   object
 5   warehouse_id            4060 non-null   object
 6   route_id                4060 non-null   object
 7   vehicle_id              4060 non-null   object
 8   customs_id              4060 non-null   object
 9   weather_id              4060 non-null   object
 10  booking_date            4060 non-null   object
 11  ship_date               4060 non-null   object
 12  expected_delivery_date  4060 non-null   object
 13  shipping_mode           4060 non-null   object
 14  shipment_type           4060 non-null   object
 15  priority                3977 non-null   object
 16  weight_kg               4060 non-null   float64
 17  volume_cbm              3972 non-null   float64
 18  declared_value          3941 non-null   float64
 19  insurance               4060 non-null   bool
 20  fragile                 4060 non-null   bool
dtypes: bool(2), float64(3), object(16)
memory usage: 610.7+ KB

In [11]:
df1.head()

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,ship_date,expected_delivery_date,shipping_mode,shipment_type,priority,weight_kg,volume_cbm,declared_value,insurance,fragile
0,2fbc2ba7-78db-4cd4-abc4-8484f8e296c0,BK100000,9d07a288-d20c-4632-be32-a80646174f82,7d9bcdf2-1cf5-4fdd-ba64-30b5ab5770fe,1b55fff6-046a-4456-9cb0-b8cd21addf5a,c8447ce1-fe0b-4d5b-96c9-b9a275ad8a25,aa747821-06b3-495f-b000-1b2e8b911707,f5ca04c7-97ce-4489-bfc9-69bb578f9273,de1b0e23-43fb-4d0d-a84a-07337bbc6411,a79111db-721a-4600-b313-ae9ab7f6f924,...,2023-08-13,2023-09-12,Sea,Import,Standard,40.6,0.12,8237.48,False,False
1,1881d036-771b-4eb6-ae7a-ac78f41dfd79,BK100001,189fab37-8b05-4e69-b000-be0f6ec9dbc4,5d909ac1-2fad-4861-a19e-79e99e125dfe,2a4ec8f6-16fe-4936-ac67-37fc52238e51,632799e1-4e31-4ba3-838e-c12663328395,1a5d3872-1ddf-4ff8-93e7-07fc5acafc25,830c2f7a-afba-4df9-b8b9-b5e5e1489cee,1d81cb99-8755-4f4a-bc2e-1bb414bbbe42,db916c48-9524-4904-b0d0-6016baeb0a3c,...,2024-06-17,2024-06-22,Rail,Export,Standard,57.1,0.22,7133.89,True,False
2,db4bcd2c-d981-4b8a-b61c-83c6dae109d8,BK100002,32320649-068b-4887-b776-ab2d9941cb1a,b1eb6a65-e462-4da5-a91f-78d00b0c241f,22c1d43a-dc69-48e3-8df1-18788f0cc19a,931ea697-c860-4af1-a6c8-e86f72c220ba,ddfeb7c4-87b1-4916-b523-22df1f1c16f3,a33fbf71-6b09-4246-921e-dd0de3c4600f,7e7b4406-6108-4603-897f-0f852c9f8927,6afe8d32-c11d-453f-9ca2-482ccc2e029d,...,2023-11-27,2023-11-28,Sea,Export,Standard,19.3,0.06,1813.83,False,True
3,b0787b6f-8743-4765-a0e8-f0457edad4bf,BK100003,f9670081-1287-4dca-9d8c-4beffacc6dcc,02c94f60-6dc8-4db8-94db-866ee6e7e608,28d939e1-9282-48ee-9a14-a7290d7e0350,a73aac58-381d-4494-84d2-de0456a1c93b,707f01ba-3ee5-4157-9845-41835b01dd03,55e1305e-cd49-4476-8b90-0ab1b3ef5e95,f7b4e378-7c54-45c1-8301-6911110a9b7e,895d6d8c-25b6-4dba-bf31-31f247df1d14,...,2025-01-17,2025-02-14,Air,Export,Standard,90.5,NaN,12633.50,True,False
4,473f319b-162e-4a31-a597-a386128b876a,BK100004,d7588951-ab24-43e4-87e7-78cf554e0eb1,a6a78e7a-331b-4e49-9a44-3040e0b2d655,75eda72c-e34b-40aa-b112-e56562058a14,57364895-d2f2-4a7e-9cd0-c2a5050d5b10,2db5db40-7365-4756-9bb7-29e3207a418d,7df258b3-189f-499d-b532-f6a016a22897,5b115244-608a-4e96-98a7-92f5acff7b54,9d00c1dc-afb4-4f76-8588-9c294802aa3c,...,2023-07-07,2023-07-30,Sea,Import,Express,745.0,3.95,178071.57,False,False

In [12]:
df1.tail()

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,ship_date,expected_delivery_date,shipping_mode,shipment_type,priority,weight_kg,volume_cbm,declared_value,insurance,fragile
4055,a7f3905a-d007-4163-996a-1d2189005f35,BK100879,3b2a4d44-a5f3-4a24-85de-433f3499ad26,eed4d7c6-cb67-4add-aa84-26c7ef19422e,aabfdc24-e492-4483-a2cc-ca4e47359860,783f84e5-d8c9-48fa-b3b0-f0cc171a9a14,bc7d0585-afbd-474c-a550-a84c12880b09,655022ff-e41b-4aae-90fc-1349b37c3a88,e5f4e9bd-a00d-4674-b0e5-e83c98f93e8c,bf3fc9c4-9026-4664-9b89-70b74556880b,...,2023-04-07,2023-04-09,Road,Import,Standard,233.8,0.81,23208.83,True,False
4056,1ceadeb5-a1a1-49f0-b077-945818042277,BK102230,25f231a5-7cc6-477f-bbac-46f86a7db9b0,d6197749-8b78-4a94-8604-67e13c4053d1,bebdea49-529d-421e-8d97-7a4698581b23,7e29426d-c596-4850-9e23-7275fb5bd2dd,6487f266-3d75-46a4-9fab-474cded00c3c,9b868b58-4b2c-49cc-9c12-4f58ea6494de,5d6226df-0185-4d0e-8e3f-2228cd859f93,a5915d20-f5ce-4ac8-8884-28855e27c5e1,...,2025-03-05,2025-04-04,Road,Import,Standard,256.0,0.82,58173.54,False,False
4057,c332c94c-2aba-45f5-b057-ba5b7d124023,BK101411,3a5f16ba-6a22-4b73-8b42-f73a731a3d47,243c3401-91f2-4230-bda0-2ab25e7c6c5d,cc0432a0-2aa4-4753-ba02-535bcd0c99a6,253629ac-11f6-4a9d-9386-ddbb18cec8bf,2f72acb2-96f9-4711-8861-bcdc723b1eef,d1dfd78e-5557-49d6-bbb0-1324183bea04,e7b7ed9e-c302-4900-95e5-58c4d35cd999,d71bf22b-bd69-47b7-9e39-0f248dbb40d5,...,2024-03-31,2024-04-04,Air,Import,Express,763.8,2.17,84758.88,False,True
4058,c05fa440-4427-46a3-823b-718a4b945ff5,BK103224,8309725c-0a5c-460f-b553-07cf3d9f45c2,2c054104-1524-4ce7-afe7-401472832930,9724bcb8-902f-4bd0-984c-62b0dda845bc,93493494-acc7-4cc8-8663-22e503ac9836,ba992640-cfb3-4e29-9ea5-3e047f48f65d,5bda03b6-463b-4a86-9446-23eef8a696a5,fdd93703-f27e-423f-8b0a-824f6713d42a,41dcd8a1-f6c1-40b2-9137-8008150ca551,...,2023-12-03,2023-12-08,Road,Import,Express,20.4,0.10,NaN,True,False
4059,77e51905-5c75-41bc-823d-4ea2fab7f75f,BK103936,b975de83-1d69-40f6-ba3b-ad9401eb018f,8b5743f6-530f-4f50-8ce0-dcceaadcbbb6,22c1d43a-dc69-48e3-8df1-18788f0cc19a,57364895-d2f2-4a7e-9cd0-c2a5050d5b10,f91e4aa3-9234-4bd3-9f92-e4657a6f19c9,c375443f-289a-4382-94ae-bb131cbe4ac3,5496a2be-7830-433a-8c72-ec39e0ce92cd,7c36ee72-f960-461c-a597-28831270ac0d,...,2024-11-13,2024-12-07,Road,Export,Express,1014.0,4.02,111440.02,True,False

In [13]:
df1.describe()

         weight_kg   volume_cbm  declared_value
count  4060.000000  3972.000000     3941.000000
mean    309.807094     1.222880    39892.919630
std     307.922457     1.324473    51424.828653
min       5.000000     0.010000       40.660000
25%      94.375000     0.350000     7558.730000
50%     217.500000     0.820000    22421.100000
75%     418.375000     1.622500    51672.200000
max    2771.000000    14.480000   579183.010000

In [14]:
df1.describe(include='all')

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,ship_date,expected_delivery_date,shipping_mode,shipment_type,priority,weight_kg,volume_cbm,declared_value,insurance,fragile
count,4060,4060,4060,4060,4060,4060,4060,4060,4060,4060,...,4060,4060,4060,4060,3977,4060.000000,3972.000000,3941.000000,4060,4060
unique,4060,4000,623,164,30,50,300,300,1617,1158,...,887,912,4,2,3,NaN,NaN,NaN,2,2
top,77e51905-5c75-41bc-823d-4ea2fab7f75f,BK100211,b38a8c2c-7dbb-4d54-a626-3419031beaaa,97425dc2-4d0e-475b-b898-869428d1629f,35b0a64d-f591-47e2-91a1-30adb2e1f912,b6236bc5-e003-45ef-8b21-fe32a07e112c,ec1aac11-e8ad-4820-a612-399ad86667b3,f0a88077-66eb-4611-bfa9-a8b6ea3f0162,def6fbd5-924b-411f-89f4-992cfed7e208,90b559f6-7035-43ba-b777-5fc0ea6ba288,...,2023-07-22,2025-02-22,Sea,Import,Standard,NaN,NaN,NaN,True,False
freq,1,2,16,38,157,96,30,25,10,11,...,12,12,1031,2035,2345,NaN,NaN,NaN,2262,3339
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,309.807094,1.222880,39892.919630,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,307.922457,1.324473,51424.828653,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.000000,0.010000,40.660000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,94.375000,0.350000,7558.730000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,217.500000,0.820000,22421.100000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,418.375000,1.622500,51672.200000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2771.000000,14.480000,579183.010000,NaN,NaN

In [15]:
df1.isnull().sum()

shipment_id                 0
booking_id                  0
customer_id                 0
product_id                  0
carrier_id                  0
warehouse_id                0
route_id                    0
vehicle_id                  0
customs_id                  0
weather_id                  0
booking_date                0
ship_date                   0
expected_delivery_date      0
shipping_mode               0
shipment_type               0
priority                   83
weight_kg                   0
volume_cbm                 88
declared_value            119
insurance                   0
fragile                     0
dtype: int64

In [16]:
df1.duplicated().sum()

np.int64(0)

In [18]:
df1.nunique()

shipment_id               4060
booking_id                4000
customer_id                623
product_id                 164
carrier_id                  30
warehouse_id                50
route_id                   300
vehicle_id                 300
customs_id                1617
weather_id                1158
booking_date               890
ship_date                  887
expected_delivery_date     912
shipping_mode                4
shipment_type                2
priority                     3
weight_kg                 2992
volume_cbm                 507
declared_value            3884
insurance                    2
fragile                      2
dtype: int64

In [19]:
# df2 = Customers

In [20]:
df2.shape

(624, 9)

In [21]:
df2.columns

Index(['customer_id', 'customer_name', 'customer_type', 'industry', 'city',
       'state', 'country', 'registration_date', 'customer_status'],
      dtype='object')

In [22]:
df2.dtypes

customer_id          object
customer_name        object
customer_type        object
industry             object
city                 object
state                object
country              object
registration_date    object
customer_status      object
dtype: object

In [23]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624 entries, 0 to 623
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        624 non-null    object
 1   customer_name      624 non-null    object
 2   customer_type      615 non-null    object
 3   industry           587 non-null    object
 4   city               624 non-null    object
 5   state              609 non-null    object
 6   country            624 non-null    object
 7   registration_date  618 non-null    object
 8   customer_status    624 non-null    object
dtypes: object(9)
memory usage: 44.0+ KB

In [24]:
df2.head()

,customer_id,customer_name,customer_type,industry,city,state,country,registration_date,customer_status
0,29a04ac8-f781-44fd-816b-f5e562061527,"Rodriguez, Figueroa and Sanchez",Business,Electronics,Pune,Maharashtra,India,2021-05-05,Active
1,3dfeb7e6-5401-425a-9cc4-e67943574bdf,Rhodes PLC,Business,Manufacturing,Singapore,Singapore,Singapore,2021-01-11,Active
2,28c08869-6ed0-4f9d-8fa8-2c1384d247e9,Johnson-Davis,Business,Manufacturing,Bengaluru,Karnataka,India,2021-11-23,Active
3,a08b0662-e4a2-4c08-a9eb-326c8122cd81,"Johnson, Gonzalez and Santos",Business,Automotive,Antwerp,Antwerp,Belgium,2023-09-29,Active
4,6848ceba-25e3-4dbb-93de-fa62f1982e62,Cole LLC,Individual,Automotive,Jeddah,Mecca,Saudi Arabia,2025-04-22,Active

In [25]:
df2.tail()

,customer_id,customer_name,customer_type,industry,city,state,country,registration_date,customer_status
619,8805c2cc-3477-46bd-91c2-7931bf85eec8,Garrison and Sons,Individual,Automotive,Karachi,Sindh,Pakistan,2021-09-12,Active
620,8309725c-0a5c-460f-b553-07cf3d9f45c2,Johnson-Davis Inc,Business,Manufacturing,Bengaluru,Karnataka,India,2021-11-23,Active
621,5d232fce-9391-4983-8f39-8773747a2f87,Cole PLC.,Individual,E-commerce,Surat,Gujarat,India,2023-05-10,Active
622,2daf04d8-7c95-4755-a5fb-9dc17fde1011,Warren Inc.,Individual,Food Processing,Hamburg,Hamburg,Germany,2026-02-10,Active
623,7cd5beff-f217-4f3e-8275-53b85b3eab67,Cooper Inc Pvt Ltd,Business,Food Processing,Rio de Janeiro,Rio de Janeiro,Brazil,2023-05-17,Inactive

In [28]:
df2.describe(include='all')

,customer_id,customer_name,customer_type,industry,city,state,country,registration_date,customer_status
count,624,624,615,587,624,609,624,618,624
unique,624,607,2,8,36,34,22,514,2
top,ac1a7179-e175-4e97-9210-4550107632a5,Davis Group,Individual,E-commerce,Rio de Janeiro,Gujarat,India,2026-02-10,Active
freq,1,2,327,94,26,33,126,4,550

In [29]:
df2.isnull().sum()

customer_id           0
customer_name         0
customer_type         9
industry             37
city                  0
state                15
country               0
registration_date     6
customer_status       0
dtype: int64

In [30]:
df2.duplicated().sum()

np.int64(0)

In [31]:
df2.nunique()

customer_id          624
customer_name        607
customer_type          2
industry               8
city                  36
state                 34
country               22
registration_date    514
customer_status        2
dtype: int64

In [33]:
# # df3 = Products

In [34]:
df3.shape

(164, 10)

In [35]:
df3.columns

Index(['product_id', 'product_name', 'category', 'hs_code', 'hazardous',
       'perishable', 'temperature_controlled', 'fragile', 'weight_per_unit',
       'supplier_name'],
      dtype='object')

In [37]:
df3.dtypes

product_id                 object
product_name               object
category                   object
hs_code                   float64
hazardous                    bool
perishable                   bool
temperature_controlled       bool
fragile                      bool
weight_per_unit           float64
supplier_name              object
dtype: object

In [38]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              164 non-null    object
 1   product_name            164 non-null    object
 2   category                164 non-null    object
 3   hs_code                 153 non-null    float64
 4   hazardous               164 non-null    bool
 5   perishable              164 non-null    bool
 6   temperature_controlled  164 non-null    bool
 7   fragile                 164 non-null    bool
 8   weight_per_unit         158 non-null    float64
 9   supplier_name           154 non-null    object
dtypes: bool(4), float64(2), object(4)
memory usage: 8.5+ KB

In [39]:
df3.head()

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
0,11ee7365-3de8-4f2e-b4b2-fc0202a0f2c3,Local Automotive Part,Automotive Parts,4022.33,False,False,True,False,7.09,Jones-Williams
1,257ace85-8350-43e8-b2f2-6161a558e97a,See Pharmaceutical,Pharmaceuticals,8365.85,False,True,False,False,16.25,Johnson LLC
2,0dad9f1e-5893-4421-b3a7-5cfec833e6ba,Raise Textile,Textiles,2667.78,False,False,False,False,31.80,Byrd and Sons
3,43fac5b7-251a-479f-88f3-c5a8e89e838d,Wonder Furniture,Furniture,9646.91,False,False,False,True,4.39,"Sanchez, Thompson and Moore"
4,373483cd-db6a-4d99-adec-0b6f9981f1ea,Opportunity Food & Beverage,Food & Beverage,8501.89,False,False,False,False,14.26,Mullen-Hall

In [40]:
df3.tail()

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
159,eac56cb7-6578-4aed-8e21-5267c69af4dc,Early Chemical,Chemicals,9571.35,False,False,False,False,4.51,Garcia Ltd
160,f5b7a533-759a-4c57-a367-4576d05294cf,Election Furniture,Furniture,2892.49,False,False,False,False,0.65,Ruiz Group
161,ea9500ea-ca7c-426f-8789-a3881557c028,Keep Textile,Textiles,2404.95,False,False,False,False,0.20,NaN
162,ef0afa43-ce55-4117-8007-c5c831f747e5,Case Food & Beverage,Food & Beverage,7089.43,False,False,True,True,11.65,NaN
163,1030dc7d-ada2-4923-8d46-4fff1712e9dc,Later Textile,Textiles,9225.96,False,False,False,False,1.14,Forbes and Sons

In [41]:
df3.describe(include='all')

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
count,164,164,164,153.000000,164,164,164,164,158.000000,154
unique,164,160,10,NaN,2,2,2,2,NaN,152
top,11ee7365-3de8-4f2e-b4b2-fc0202a0f2c3,Keep Textile,Automotive Parts,NaN,False,False,False,False,NaN,Forbes and Sons
freq,1,2,20,NaN,153,138,136,130,NaN,2
mean,NaN,NaN,NaN,5200.495163,NaN,NaN,NaN,NaN,8.183544,NaN
std,NaN,NaN,NaN,2741.522349,NaN,NaN,NaN,NaN,7.838489,NaN
min,NaN,NaN,NaN,1017.370000,NaN,NaN,NaN,NaN,0.200000,NaN
25%,NaN,NaN,NaN,2715.190000,NaN,NaN,NaN,NaN,2.532500,NaN
50%,NaN,NaN,NaN,4707.980000,NaN,NaN,NaN,NaN,5.755000,NaN
75%,NaN,NaN,NaN,7520.740000,NaN,NaN,NaN,NaN,11.740000,NaN
max,NaN,NaN,NaN,9849.430000,NaN,NaN,NaN,NaN,49.230000,NaN

In [42]:
df3.isnull().sum()

product_id                 0
product_name               0
category                   0
hs_code                   11
hazardous                  0
perishable                 0
temperature_controlled     0
fragile                    0
weight_per_unit            6
supplier_name             10
dtype: int64

In [43]:
df3.duplicated().sum()

np.int64(0)

In [44]:
df3.nunique()

product_id                164
product_name              160
category                   10
hs_code                   149
hazardous                   2
perishable                  2
temperature_controlled      2
fragile                     2
weight_per_unit           145
supplier_name             152
dtype: int64

In [45]:
df4

,carrier_id,carrier_name,carrier_type,average_rating,fleet_size,years_of_service,headquarters
0,8ece1ccd-e714-4f7e-9cbe-ae2b70fbfe8e,Adams Ltd Freight,Rail,3.42,174.0,16,Mumbai
1,3da6490d-b4a8-4ae9-8e6f-bc2b4559e53f,Gallagher and Sons Logistics,Road,4.76,469.0,8,Vancouver
2,3b435d96-04e0-4c24-b4f2-2f00145cb906,"Bradford, Salinas and Kelly Freight",Road,2.53,404.0,33,Surat
3,dbad2d39-550a-4a63-a01f-02661e0e712b,Thompson PLC Logistics,Sea,4.15,NaN,15,Rio de Janeiro
4,e939f0cc-3244-40b3-884d-8f4e71455344,Drake-Wolfe Cargo,Sea,3.12,242.0,4,Kolkata
5,f4a1d068-524c-4984-bf24-382f49c070be,"Johnson, Haynes and Meza Freight",Road,4.98,441.0,19,Ho Chi Minh City
6,75eda72c-e34b-40aa-b112-e56562058a14,"Thomas, Vaughan and Copeland Cargo",Rail,5.00,383.0,8,Kolkata
7,3ee36a0b-8b6e-4319-9a46-7e2a1a3c5c9f,Weaver-Thompson Logistics,Road,2.99,441.0,9,Shanghai
8,cd27af18-3511-4c48-8009-6faa38c43d66,Davis and Sons Cargo,Sea,3.16,462.0,29,Los Angeles
9,d8201f6d-7b3f-4b8f-9d30-391c61520987,"Robinson, Fox and Smith Logistics",Sea,4.29,NaN,22,Shenzhen
10,9724bcb8-902f-4bd0-984c-62b0dda845bc,"Harris, Anderson and Love Logistics",Rail,3.29,209.0,30,Los Angeles
11,640dad23-52ce-4ff4-a2aa-062806766c1d,Brown-Hernandez Shipping,Rail,3.56,414.0,27,Shanghai
12,73948ff8-80a9-41bd-9f09-d94527525731,"Stark, Schroeder and Mathis Logistics",Air,3.62,361.0,4,Shanghai
13,cc0432a0-2aa4-4753-ba02-535bcd0c99a6,Yu-Brooks Logistics,Rail,2.06,471.0,38,Toronto
14,22c1d43a-dc69-48e3-8df1-18788f0cc19a,"Foster, Garcia and Turner Shipping",Air,3.59,317.0,25,Jakarta
15,c8fc4b77-1094-4e74-a2a1-184a1249cc61,Daugherty Ltd Logistics,Air,3.05,252.0,32,Pune
16,65301b38-fa49-41db-bed3-e17ce18b2cfc,Conner-Yu Shipping,Rail,3.21,28.0,5,New York
17,c778e652-6e62-48d0-8ab5-4fb8a8b7ca14,"Stewart, Mann and Hoffman Cargo",Road,4.75,365.0,34,Rotterdam
18,1b845b07-34b8-476c-a918-4315bdd88d07,"Buchanan, Walker and Chapman Cargo",Road,2.59,226.0,16,Toronto
19,2a4ec8f6-16fe-4936-ac67-37fc52238e51,Gray Ltd Cargo,Rail,4.25,81.0,36,Chennai
20,d4ec6b52-c85f-4cb6-b86f-3a0d84363654,"Phillips, Thompson and Smith Logistics",Air,3.38,263.0,31,Vancouver
21,35b0a64d-f591-47e2-91a1-30adb2e1f912,"Fry, Myers and Gamble Freight",Road,3.38,389.0,32,Colombo
22,7ea1ac7e-7232-4178-aef1-f91bef87c9c6,"Johnson, Guzman and Mccall Freight",Sea,4.23,147.0,4,Antwerp
23,33cf5931-ba67-4b99-9de6-685589a6646f,"Walker, Cunningham and Zuniga Freight",Rail,3.87,211.0,16,Ahmedabad
24,28d939e1-9282-48ee-9a14-a7290d7e0350,Rivera Inc Shipping,Rail,4.06,415.0,37,Sao Paulo
25,2091e662-39cf-489c-9e58-8066d5101a55,Reed LLC Logistics,Rail,4.37,233.0,21,Pune
26,bebdea49-529d-421e-8d97-7a4698581b23,Fields Inc Shipping,Road,3.33,57.0,26,Melbourne
27,aabfdc24-e492-4483-a2cc-ca4e47359860,"Santiago, Daniel and Rogers Logistics",Road,3.11,427.0,6,London
28,c3b1b3c0-b731-41b7-9fff-aefd5e586db0,Baker and Sons Freight,Rail,2.73,491.0,22,Ho Chi Minh City
29,1b55fff6-046a-4456-9cb0-b8cd21addf5a,"Jones, Scott and Rodriguez Logistics",Air,2.94,437.0,30,Karachi

In [46]:
# df4 = Carriers

In [48]:
df4.shape

(30, 7)

In [52]:
df4.columns

Index(['carrier_id', 'carrier_name', 'carrier_type', 'average_rating',
       'fleet_size', 'years_of_service', 'headquarters'],
      dtype='object')

In [55]:
df4.dtypes

carrier_id           object
carrier_name         object
carrier_type         object
average_rating      float64
fleet_size          float64
years_of_service      int64
headquarters         object
dtype: object

In [56]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   carrier_id        30 non-null     object
 1   carrier_name      30 non-null     object
 2   carrier_type      30 non-null     object
 3   average_rating    30 non-null     float64
 4   fleet_size        28 non-null     float64
 5   years_of_service  30 non-null     int64
 6   headquarters      30 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.8+ KB

In [57]:
df4.head()

,carrier_id,carrier_name,carrier_type,average_rating,fleet_size,years_of_service,headquarters
0,8ece1ccd-e714-4f7e-9cbe-ae2b70fbfe8e,Adams Ltd Freight,Rail,3.42,174.0,16,Mumbai
1,3da6490d-b4a8-4ae9-8e6f-bc2b4559e53f,Gallagher and Sons Logistics,Road,4.76,469.0,8,Vancouver
2,3b435d96-04e0-4c24-b4f2-2f00145cb906,"Bradford, Salinas and Kelly Freight",Road,2.53,404.0,33,Surat
3,dbad2d39-550a-4a63-a01f-02661e0e712b,Thompson PLC Logistics,Sea,4.15,NaN,15,Rio de Janeiro
4,e939f0cc-3244-40b3-884d-8f4e71455344,Drake-Wolfe Cargo,Sea,3.12,242.0,4,Kolkata

In [58]:
df4.tail()

,carrier_id,carrier_name,carrier_type,average_rating,fleet_size,years_of_service,headquarters
25,2091e662-39cf-489c-9e58-8066d5101a55,Reed LLC Logistics,Rail,4.37,233.0,21,Pune
26,bebdea49-529d-421e-8d97-7a4698581b23,Fields Inc Shipping,Road,3.33,57.0,26,Melbourne
27,aabfdc24-e492-4483-a2cc-ca4e47359860,"Santiago, Daniel and Rogers Logistics",Road,3.11,427.0,6,London
28,c3b1b3c0-b731-41b7-9fff-aefd5e586db0,Baker and Sons Freight,Rail,2.73,491.0,22,Ho Chi Minh City
29,1b55fff6-046a-4456-9cb0-b8cd21addf5a,"Jones, Scott and Rodriguez Logistics",Air,2.94,437.0,30,Karachi

In [59]:
df4.describe(include='all')

,carrier_id,carrier_name,carrier_type,average_rating,fleet_size,years_of_service,headquarters
count,30,30,30,30.000000,28.000000,30.000000,30
unique,30,30,4,NaN,NaN,NaN,22
top,8ece1ccd-e714-4f7e-9cbe-ae2b70fbfe8e,Adams Ltd Freight,Rail,NaN,NaN,NaN,Shanghai
freq,1,1,11,NaN,NaN,NaN,3
mean,NaN,NaN,NaN,3.592333,314.642857,21.166667,NaN
std,NaN,NaN,NaN,0.754900,136.456265,11.255905,NaN
min,NaN,NaN,NaN,2.060000,28.000000,4.000000,NaN
25%,NaN,NaN,NaN,3.112500,222.250000,10.500000,NaN
50%,NaN,NaN,NaN,3.400000,363.000000,22.000000,NaN
75%,NaN,NaN,NaN,4.210000,429.500000,30.750000,NaN
max,NaN,NaN,NaN,5.000000,491.000000,38.000000,NaN

In [60]:
df4.isnull().sum()

carrier_id          0
carrier_name        0
carrier_type        0
average_rating      0
fleet_size          2
years_of_service    0
headquarters        0
dtype: int64

In [61]:
df4.duplicated().sum()

np.int64(0)

In [63]:
df4.nunique()

carrier_id          30
carrier_name        30
carrier_type         4
average_rating      29
fleet_size          27
years_of_service    22
headquarters        22
dtype: int64

In [65]:
# df5 == route

In [66]:
df5.shape

(300, 11)

In [68]:
df5.columns

Index(['route_id', 'origin_city', 'destination_city', 'origin_country',
       'destination_country', 'origin_port', 'destination_port', 'distance_km',
       'average_transit_days', 'route_risk', 'traffic_index'],
      dtype='object')

In [71]:
df5.dtypes

route_id                 object
origin_city              object
destination_city         object
origin_country           object
destination_country      object
origin_port              object
destination_port         object
distance_km             float64
average_transit_days      int64
route_risk               object
traffic_index           float64
dtype: object

In [73]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   route_id              300 non-null    object
 1   origin_city           300 non-null    object
 2   destination_city      300 non-null    object
 3   origin_country        300 non-null    object
 4   destination_country   300 non-null    object
 5   origin_port           300 non-null    object
 6   destination_port      300 non-null    object
 7   distance_km           300 non-null    float64
 8   average_transit_days  300 non-null    int64
 9   route_risk            294 non-null    object
 10  traffic_index         291 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 25.9+ KB

In [74]:
df5.head()

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
0,9e78f107-814c-477e-9d1f-45f98e13055d,Jeddah,Chicago,Saudi Arabia,USA,Port of Jeddah,Port of Chicago,12023.7,17,Low,99.0
1,53dfd4ec-4ed2-41fa-ab72-e023d823a48b,Ho Chi Minh City,Antwerp,Vietnam,Belgium,Port of Ho Chi Minh City,Port of Antwerp,13967.0,15,Medium,63.0
2,fb541cb9-674f-4ace-a42f-d329f4695f5e,Bengaluru,Chicago,India,USA,Port of Bengaluru,Port of Chicago,3441.6,7,High,42.0
3,6a1da14d-b39f-4fd7-82ac-0eab1209299f,Antwerp,Ahmedabad,Belgium,India,Port of Antwerp,Port of Ahmedabad,641.7,6,High,99.0
4,f01765d1-46b8-4301-ae38-c3d463322c21,Jeddah,Mumbai,Saudi Arabia,India,Port of Jeddah,Port of Mumbai,5803.8,7,Medium,NaN

In [76]:
df5.tail()

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
295,9962d450-44ea-4af9-ad26-3459d7875481,Jeddah,Singapore,Saudi Arabia,Singapore,Port of Jeddah,Port of Singapore,9524.7,11,Low,58.0
296,fe29039e-5f23-4576-b1f6-6e539620aae3,Delhi,Shenzhen,India,China,Port of Delhi,Port of Shenzhen,4500.3,29,Low,92.0
297,22c1a25e-190d-488d-8117-fd1f76720e05,Hong Kong,Rio de Janeiro,China,Brazil,Port of Hong Kong,Port of Rio de Janeiro,11885.7,11,Low,89.0
298,2db5db40-7365-4756-9bb7-29e3207a418d,Shanghai,Pune,China,India,Port of Shanghai,Port of Pune,13264.5,23,Low,58.0
299,c0aafcd0-b7c6-482e-a9d2-acf24c3eb138,Ho Chi Minh City,Ahmedabad,Vietnam,India,Port of Ho Chi Minh City,Port of Ahmedabad,12397.2,13,Medium,94.0

In [77]:
df5.describe(include='all')

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
count,300,300,300,300,300,300,300,300.000000,300.000000,294,291.000000
unique,300,36,36,22,22,36,36,NaN,NaN,3,NaN
top,c0aafcd0-b7c6-482e-a9d2-acf24c3eb138,Sydney,New York,India,India,Port of Sydney,Port of New York,NaN,NaN,Low,NaN
freq,1,15,16,61,51,15,16,NaN,NaN,145,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6996.766333,15.156667,NaN,51.786942
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4030.600619,8.651877,NaN,29.252338
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.100000,1.000000,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3336.525000,7.000000,NaN,27.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6893.950000,16.000000,NaN,53.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10673.225000,22.000000,NaN,76.500000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13993.800000,30.000000,NaN,100.000000

In [78]:
df5.isnull().sum()

route_id                0
origin_city             0
destination_city        0
origin_country          0
destination_country     0
origin_port             0
destination_port        0
distance_km             0
average_transit_days    0
route_risk              6
traffic_index           9
dtype: int64

In [79]:
df5.duplicated().sum()

np.int64(0)

In [80]:
df5.nunique()

route_id                300
origin_city              36
destination_city         36
origin_country           22
destination_country      22
origin_port              36
destination_port         36
distance_km             300
average_transit_days     30
route_risk                3
traffic_index            98
dtype: int64

In [82]:
# df6 == vehicles

In [83]:
df6.shape

(300, 7)

In [84]:
df6.columns

Index(['vehicle_id', 'vehicle_number', 'vehicle_type', 'capacity_kg',
       'fuel_type', 'maintenance_status', 'vehicle_age'],
      dtype='object')

In [86]:
df6.dtypes

vehicle_id            object
vehicle_number        object
vehicle_type          object
capacity_kg            int64
fuel_type             object
maintenance_status    object
vehicle_age            int64
dtype: object

In [87]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          300 non-null    object
 1   vehicle_number      300 non-null    object
 2   vehicle_type        300 non-null    object
 3   capacity_kg         300 non-null    int64
 4   fuel_type           293 non-null    object
 5   maintenance_status  291 non-null    object
 6   vehicle_age         300 non-null    int64
dtypes: int64(2), object(5)
memory usage: 16.5+ KB

In [88]:
df6.head()

,vehicle_id,vehicle_number,vehicle_type,capacity_kg,fuel_type,maintenance_status,vehicle_age
0,503f709e-75f9-41fd-be6b-1babec9a3302,UA-0067-KA,Aircraft,25317,Marine Fuel,Good,24
1,290d13af-045d-4e54-af2c-83645a3392a1,YG-7658-EY,Aircraft,22467,Marine Fuel,Due,4
2,2139f3fc-b192-472c-8ea0-1e4d5bb59e2b,EZ-9327-CS,Aircraft,9976,Petrol,Due,1
3,fdc3ac91-fdbd-48b4-8353-06b19104187f,EV-0541-KY,Wagon,20689,Electric,Due,14
4,830c2f7a-afba-4df9-b8b9-b5e5e1489cee,VM-2181-NE,Ship,12342,Diesel,Due,6

In [89]:
df6.tail()

,vehicle_id,vehicle_number,vehicle_type,capacity_kg,fuel_type,maintenance_status,vehicle_age
295,c5d421d4-202c-4f89-8759-362a182b9f97,WM-2067-KG,Wagon,7895,Electric,Good,3
296,35e02879-74af-4235-be33-78a28680f7da,YZ-1364-JI,Aircraft,32993,Electric,Good,17
297,9f72dda8-ce2b-46d5-8bfc-9957502789ab,VD-5179-JZ,Truck,5890,Electric,Good,12
298,aaf1471d-3130-4883-9fb8-5782ed8b1d4e,BX-4168-SI,Ship,30446,Marine Fuel,Due,21
299,e29fdd8b-429b-4c8a-b253-c2b7f14120ce,FZ-2783-PK,Wagon,15302,Marine Fuel,Good,13

In [90]:
df6.describe(include='all')

,vehicle_id,vehicle_number,vehicle_type,capacity_kg,fuel_type,maintenance_status,vehicle_age
count,300,300,300,300.000000,293,291,300.000000
unique,300,300,4,NaN,6,3,NaN
top,e29fdd8b-429b-4c8a-b253-c2b7f14120ce,FZ-2783-PK,Truck,NaN,Jet Fuel,Good,NaN
freq,1,1,87,NaN,60,205,NaN
mean,NaN,NaN,NaN,20563.953333,NaN,NaN,12.600000
std,NaN,NaN,NaN,11279.617954,NaN,NaN,7.539861
min,NaN,NaN,NaN,555.000000,NaN,NaN,0.000000
25%,NaN,NaN,NaN,10733.750000,NaN,NaN,6.000000
50%,NaN,NaN,NaN,20860.000000,NaN,NaN,13.000000
75%,NaN,NaN,NaN,30262.250000,NaN,NaN,19.250000
max,NaN,NaN,NaN,39939.000000,NaN,NaN,25.000000

In [91]:
df6.isnull().sum()

vehicle_id            0
vehicle_number        0
vehicle_type          0
capacity_kg           0
fuel_type             7
maintenance_status    9
vehicle_age           0
dtype: int64

In [92]:
df6.duplicated().sum()

np.int64(0)

In [93]:
df6.nunique()

vehicle_id            300
vehicle_number        300
vehicle_type            4
capacity_kg           300
fuel_type               6
maintenance_status      3
vehicle_age            26
dtype: int64

In [95]:
# df7 == warehouse

In [97]:
df7.shape

(50, 7)

In [98]:
df7.columns

Index(['warehouse_id', 'warehouse_name', 'city', 'state', 'warehouse_capacity',
       'current_utilization', 'warehouse_type'],
      dtype='object')

In [99]:
df7.dtypes

warehouse_id            object
warehouse_name          object
city                    object
state                   object
warehouse_capacity     float64
current_utilization    float64
warehouse_type          object
dtype: object

In [100]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   warehouse_id         50 non-null     object
 1   warehouse_name       50 non-null     object
 2   city                 50 non-null     object
 3   state                50 non-null     object
 4   warehouse_capacity   50 non-null     float64
 5   current_utilization  48 non-null     float64
 6   warehouse_type       50 non-null     object
dtypes: float64(2), object(5)
memory usage: 2.9+ KB

In [101]:
df7.head()

,warehouse_id,warehouse_name,city,state,warehouse_capacity,current_utilization,warehouse_type
0,95cb7f61-7030-488e-a21e-f25881fa9392,Istanbul Fulfillment Center,Istanbul,Istanbul,16503.0,52.6,Distribution
1,4e0a9685-3e0b-44a1-95d5-098f03a84068,Sao Paulo Regional Hub,Sao Paulo,Sao Paulo,4736.0,80.7,Regional
2,e692eb32-69c3-4aa2-aab7-8008643ca9ff,Mumbai Distribution Center,Mumbai,Maharashtra,12185.0,17.3,Distribution
3,c8688269-f520-41b9-a3c3-4eb7d3666cfc,Istanbul Distribution Center,Istanbul,Istanbul,18104.0,70.1,Regional
4,b09d1a21-0bc8-46ab-b707-d9c6c09981fd,Bengaluru Distribution Center,Bengaluru,Karnataka,6379.0,76.6,Regional

In [102]:
df7.tail()

,warehouse_id,warehouse_name,city,state,warehouse_capacity,current_utilization,warehouse_type
45,a4867d58-a0f0-4818-a601-293f1e26b52f,Karachi Distribution Center,Karachi,Sindh,11848.0,60.2,Distribution
46,3e2e92a7-33ba-4679-b703-02bddd753301,Tokyo Distribution Center,Tokyo,Tokyo,18383.0,32.5,Regional
47,7e9e597b-833f-4a1b-bc64-dbfbe0c2931e,Pune Distribution Center,Pune,Maharashtra,12337.0,82.4,Regional
48,87e0260b-6980-422c-aff0-2cf55d9eead4,Hamburg Fulfillment Center,Hamburg,Hamburg,2306.0,57.3,Distribution
49,00b71ef8-acb3-4009-9050-e34379c33d39,Bangkok Distribution Center,Bangkok,Bangkok,4715.0,46.2,Distribution

In [103]:
df7.describe(include='all')

,warehouse_id,warehouse_name,city,state,warehouse_capacity,current_utilization,warehouse_type
count,50,50,50,50,50.00000,48.000000,50
unique,50,40,26,24,NaN,NaN,2
top,95cb7f61-7030-488e-a21e-f25881fa9392,Istanbul Regional Hub,Istanbul,Istanbul,NaN,NaN,Distribution
freq,1,3,6,6,NaN,NaN,25
mean,NaN,NaN,NaN,NaN,10589.58000,68.127083,NaN
std,NaN,NaN,NaN,NaN,5447.12689,19.733002,NaN
min,NaN,NaN,NaN,NaN,1142.00000,17.300000,NaN
25%,NaN,NaN,NaN,NaN,5771.00000,53.650000,NaN
50%,NaN,NaN,NaN,NaN,11141.50000,69.050000,NaN
75%,NaN,NaN,NaN,NaN,14445.00000,82.550000,NaN
max,NaN,NaN,NaN,NaN,19092.00000,100.000000,NaN

In [104]:
df7.isnull().sum()

warehouse_id           0
warehouse_name         0
city                   0
state                  0
warehouse_capacity     0
current_utilization    2
warehouse_type         0
dtype: int64

In [105]:
df7.duplicated().sum()

np.int64(0)

In [106]:
df7.nunique()

warehouse_id           50
warehouse_name         40
city                   26
state                  24
warehouse_capacity     50
current_utilization    47
warehouse_type          2
dtype: int64

In [108]:
# df8 == customs

In [110]:
df8.shape

(1800, 6)

In [112]:
df8.columns

Index(['customs_id', 'customs_required', 'documentation_complete',
       'inspection_required', 'cargo_type', 'destination_country'],
      dtype='object')

In [113]:
df8.dtypes

customs_id                object
customs_required            bool
documentation_complete    object
inspection_required       object
cargo_type                object
destination_country       object
dtype: object

In [114]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customs_id              1800 non-null   object
 1   customs_required        1800 non-null   bool
 2   documentation_complete  1764 non-null   object
 3   inspection_required     1745 non-null   object
 4   cargo_type              1800 non-null   object
 5   destination_country     1800 non-null   object
dtypes: bool(1), object(5)
memory usage: 72.2+ KB

In [115]:
df8.head()

,customs_id,customs_required,documentation_complete,inspection_required,cargo_type,destination_country
0,d7ddd34e-151b-4058-b8ee-93ed4c6826ae,False,True,False,Pharmaceuticals,UK
1,39f37e26-87c5-4e2e-aa18-7cf922148905,True,True,False,Food & Beverage,India
2,8679a64b-484b-4cc6-b937-c3fe7de7c513,True,True,True,Textiles,China
3,efc4456c-e459-445a-b456-c2150ca8aa87,True,True,False,Furniture,India
4,516ee0f2-6417-4038-98fa-703ac7a53938,False,True,False,Automotive Parts,Belgium

In [116]:
df8.tail()

,customs_id,customs_required,documentation_complete,inspection_required,cargo_type,destination_country
1795,3e591d21-b0a5-4a7f-9a54-93f57872f5cb,False,True,False,Toys,Thailand
1796,f469d5f7-b214-4480-82cc-0509cce029a6,True,True,False,Machinery,Canada
1797,7506c6cf-9b10-4a2d-b800-ba9866fac22a,False,True,False,Pharmaceuticals,South Africa
1798,427dc692-ee88-411d-9cb1-ae090c895805,True,True,False,Chemicals,Australia
1799,1bf05663-b5a9-4f2d-a41c-f770c21784d7,True,True,False,Toys,China

In [117]:
df8.describe(include='all')

,customs_id,customs_required,documentation_complete,inspection_required,cargo_type,destination_country
count,1800,1800,1764,1745,1800,1800
unique,1800,2,2,2,10,22
top,1bf05663-b5a9-4f2d-a41c-f770c21784d7,True,True,False,Agricultural Goods,India
freq,1,1161,1543,1475,189,395

In [119]:
df8.isnull().sum()

customs_id                 0
customs_required           0
documentation_complete    36
inspection_required       55
cargo_type                 0
destination_country        0
dtype: int64

In [120]:
df8.duplicated().sum()

np.int64(0)

In [121]:
df8.nunique()

customs_id                1800
customs_required             2
documentation_complete       2
inspection_required          2
cargo_type                  10
destination_country         22
dtype: int64

In [122]:
# df9 == weather

In [123]:
df9.shape

(1200, 9)

In [124]:
df9.columns

Index(['weather_id', 'city', 'forecast_date', 'weather_condition',
       'temperature', 'rainfall', 'humidity', 'wind_speed', 'visibility'],
      dtype='object')

In [125]:
df9.dtypes

weather_id            object
city                  object
forecast_date         object
weather_condition     object
temperature          float64
rainfall             float64
humidity             float64
wind_speed           float64
visibility           float64
dtype: object

In [126]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   weather_id         1200 non-null   object
 1   city               1200 non-null   object
 2   forecast_date      1200 non-null   object
 3   weather_condition  1200 non-null   object
 4   temperature        1200 non-null   float64
 5   rainfall           1200 non-null   float64
 6   humidity           1174 non-null   float64
 7   wind_speed         1153 non-null   float64
 8   visibility         1133 non-null   float64
dtypes: float64(5), object(4)
memory usage: 84.5+ KB

In [127]:
df9.head()

,weather_id,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
0,7f327cfc-072b-47fd-81b5-08ed38e119d1,Hong Kong,2024-12-04,Fog,40.2,0.1,79.3,6.3,8.9
1,5aba2404-ccd6-4d6d-9ad9-71089bdfa0a3,Toronto,2025-10-19,Fog,18.8,0.2,35.6,1.5,9.2
2,65e3caca-a1f2-478d-94db-17517cb90694,Ho Chi Minh City,2026-01-18,Clear,7.0,0.1,80.8,3.3,9.8
3,ba11fa28-8f93-4833-8c95-a78d4623637e,Vancouver,2025-01-11,Rain,28.4,3.6,90.5,0.4,7.0
4,23708f5e-5275-4b0f-a800-e5bf89b698e7,Sydney,2024-08-31,Cloudy,14.2,0.1,79.5,20.1,NaN

In [128]:
df9.tail()

,weather_id,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
1195,1243ce89-445c-417b-8e30-a17a5674754f,Melbourne,2025-03-26,Rain,-5.8,2.0,68.0,5.8,8.8
1196,da3567bb-69ec-4fc5-9024-a4de8ebb5557,Shenzhen,2025-04-17,Cloudy,-7.1,0.1,85.5,0.7,9.4
1197,50c68b8a-8d28-4e10-af3e-2a08a2c76235,Jakarta,2025-08-22,Storm,-5.2,7.2,48.9,14.2,2.0
1198,264b9a4b-f4a1-4da1-89ff-3babcef1b98a,Antwerp,2024-11-08,Clear,-6.6,0.1,30.2,3.0,8.1
1199,0b45dc62-119b-4e58-ba13-cfc7c15372a4,Cape Town,2025-02-22,Cloudy,20.6,0.5,72.5,7.5,7.6

In [130]:
df9.describe(include='all')

,weather_id,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
count,1200,1200,1200,1200,1200.000000,1200.000000,1174.000000,1153.000000,1133.000000
unique,1200,36,600,6,NaN,NaN,NaN,NaN,NaN
top,b45c0e42-772c-418c-8bcd-82d30b6a0680,Vancouver,2024-11-21,Clear,NaN,NaN,NaN,NaN,NaN
freq,1,45,8,469,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,15.590000,1.296250,60.406474,8.003643,7.284554
std,NaN,NaN,NaN,NaN,14.680313,2.608435,22.463881,8.124203,2.084843
min,NaN,NaN,NaN,NaN,-10.000000,0.000000,20.000000,0.000000,0.600000
25%,NaN,NaN,NaN,NaN,2.600000,0.100000,41.500000,2.400000,6.500000
50%,NaN,NaN,NaN,NaN,15.350000,0.300000,60.050000,5.400000,7.700000
75%,NaN,NaN,NaN,NaN,27.750000,0.900000,79.475000,11.000000,8.800000
max,NaN,NaN,NaN,NaN,41.900000,19.900000,100.000000,63.200000,10.000000

In [131]:
df9.isnull().sum()

weather_id            0
city                  0
forecast_date         0
weather_condition     0
temperature           0
rainfall              0
humidity             26
wind_speed           47
visibility           67
dtype: int64

In [132]:
df9.duplicated().sum()

np.int64(0)

In [133]:
df9.nunique()

weather_id           1200
city                   36
forecast_date         600
weather_condition       6
temperature           483
rainfall              105
humidity              620
wind_speed            261
visibility             91
dtype: int64

In [134]:
# df10 == shipment_delivery_history

In [135]:
df10.shape

(4020, 5)

In [137]:
df10.columns

Index(['history_id', 'shipment_id', 'actual_delivery_date', 'delivery_status',
       'delivery_attempts'],
      dtype='object')

In [138]:
df10.dtypes

history_id               object
shipment_id              object
actual_delivery_date     object
delivery_status          object
delivery_attempts       float64
dtype: object

In [139]:
df10.head()

,history_id,shipment_id,actual_delivery_date,delivery_status,delivery_attempts
0,d945d0ad-965e-4f75-a076-ad3e6df04011,2fbc2ba7-78db-4cd4-abc4-8484f8e296c0,2023-09-15,Delivered,2.0
1,1efbf0f3-db41-447b-bc9f-da1197fe9b73,1881d036-771b-4eb6-ae7a-ac78f41dfd79,2024-06-23,Delivered,1.0
2,2a991dc6-0cc1-4b90-8ee7-32014f1a8572,db4bcd2c-d981-4b8a-b61c-83c6dae109d8,2023-11-28,Delivered,1.0
3,bfe64b48-6caf-435b-a4ca-b1b9eb69eb19,b0787b6f-8743-4765-a0e8-f0457edad4bf,2025-02-17,Delivered,2.0
4,3fbcabd9-087a-4e57-b42e-5cdddd2ad9f1,473f319b-162e-4a31-a597-a386128b876a,2023-07-30,Delivered,1.0

In [140]:
df10.tail()

,history_id,shipment_id,actual_delivery_date,delivery_status,delivery_attempts
4015,8bacefae-32a9-4a46-a218-dce060aa8336,a7f3905a-d007-4163-996a-1d2189005f35,2023-04-16,Delivered,3.0
4016,3da49ce5-4414-4c0b-91d5-e5e7c537680e,1ceadeb5-a1a1-49f0-b077-945818042277,2025-04-04,Delivered,1.0
4017,bac185d7-feec-43ca-95f8-7dfce4889b3b,c332c94c-2aba-45f5-b057-ba5b7d124023,2024-04-04,Delivered,1.0
4018,2b5e17a5-ac67-4941-97b0-d9eadd08681c,c05fa440-4427-46a3-823b-718a4b945ff5,2023-12-09,Delivered,1.0
4019,5fefd64b-1e80-4c57-9078-b8ba9ce614a5,77e51905-5c75-41bc-823d-4ea2fab7f75f,2024-12-11,Delivered,1.0

In [141]:
df10.describe(include='all')

,history_id,shipment_id,actual_delivery_date,delivery_status,delivery_attempts
count,4020,4020,4020,4020,3942.000000
unique,4020,4020,909,2,NaN
top,5fefd64b-1e80-4c57-9078-b8ba9ce614a5,77e51905-5c75-41bc-823d-4ea2fab7f75f,2023-09-06,Delivered,NaN
freq,1,1,12,3863,NaN
mean,NaN,NaN,NaN,NaN,1.235667
std,NaN,NaN,NaN,NaN,0.537379
min,NaN,NaN,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,1.000000
50%,NaN,NaN,NaN,NaN,1.000000
75%,NaN,NaN,NaN,NaN,1.000000
max,NaN,NaN,NaN,NaN,3.000000

In [142]:
df10.isnull().sum()

history_id               0
shipment_id              0
actual_delivery_date     0
delivery_status          0
delivery_attempts       78
dtype: int64

In [143]:
df10.duplicated().sum()

np.int64(0)

In [144]:
df10.nunique()

history_id              4020
shipment_id             4020
actual_delivery_date     909
delivery_status            2
delivery_attempts          3
dtype: int64